<!--FILTER CATEGORY
-----------

"id": "${filterName}"
,"count": ${status.count}
,"type": "CategoryFilter"
<c:if test="${elem.value.Label.isSet}">,"label": "${elem.value.Label}"</c:if>
<c:if test="${elem.value.Placeholder.isSet}">,"placeholder": "${elem.value.Placeholder}"</c:if>
,"solr": "${elem.value.FieldSolr}"
,"class": "${filterClass}"
,"categoryRoot": "${CategoryRoot}"
,"treeFolder": "${TreeFolder}"
,"showParent": "${ShowParent}"
,"showEmptyOption": "${!elem.value.ShowEmptyOption.exists or elem.value.ShowEmptyOption=='true'}"
,"labelCategoryFilterAll": "${LabelCategoryFilterAll}"
,"fieldType": "${elem.value.FieldType}"
,"categories": ${categoriesFilter}
,"value": "${filterValue}"
-->

<template>
    <v-filter-category-select v-if="vFilter.fieldType === 'select'" :vFilter="vFilter"></v-filter-category-select>

        <!--</c:when>
        <c:when test="${elem.value.FieldType == 'selectmultiple' }">
            <div class="block-drop">
                <select class="form-control" name="${fieldName}" id="${fieldName}"
                        multiple>
                    <%
                    String
                    [
                    ]
                    fieldValuesArray
                    =
                    request
                    .
                    getParameterValues
                    (
                    fieldName
                    )
                    ;
                    List
                    <
                    String
                    >
                    fieldValues
                    =
                    null
                    ;
                    String
                    categoryProperty
                    =
                    (
                    String
                    )
                    request
                    .
                    getAttribute
                    (
                    "filtercategoryProperty"
                    )
                    ;

                    if
                    (
                    fieldValuesArray
                    !=
                    null
                    )
                    fieldValues
                    =
                    Arrays
                    .
                    asList
                    (
                    fieldValuesArray
                    )
                    ;
                    // si nos llega el parametro vacio guardamos la propiedad de categoria definida (si es que existe) como fieldvalue para que se muestre seleccionada
                    else
                    if
                    (
                    !
                    StringUtils
                    .
                    isBlank
                    (
                    categoryProperty
                    )
                    )
                    {
                    fieldValues
                    =
                    new
                    ArrayList
                    <
                    String
                    >
                    (
                    )
                    ;
                    fieldValues
                    .
                    add
                    (
                    categoryProperty
                    )
                    ;
                    }
                    else
                    fieldValues
                    =
                    new
                    ArrayList
                    <
                    String
                    >
                    (
                    )
                    ;
                    if
                    (
                    tituloCatPadre
                    !=
                    null
                    )
                    {
                    if
                    (
                    fieldValues
                    .
                    contains
                    (
                    categoryRoot
                    )
                    )
                    out
                    .
                    println
                    (
                    "<option value=\""
                             +
                             categoryRoot
                             +
                    "\" selected=\"selected\">"
                    +
                    tituloCatPadre
                    +
                    "</option>"
                    )
                    ;
                    else
                    out
                    .
                    println
                    (
                    "<option value=\""
                             +
                             categoryRoot
                             +
                    "\">"
                    +
                    tituloCatPadre
                    +
                    "</option>"
                    )
                    ;
                    }
                    for
                    (
                    CmsCategory
                    cat
                    :
                    categorias
                    )
                    {
                    String
                    titleCat
                    =
                    ""
                    ;
                    //Primero intentamos leer la categoria Title_LOCALE, si no nos quedamos con el Title
                    try
                    {
                    String
                    site
                    =
                    OpenCms
                    .
                    getSiteManager
                    (
                    )
                    .
                    getCurrentSite
                    (
                    cmso
                    )
                    .
                    getSiteRoot
                    (
                    )
                    ;
                    String
                    pathResourceCat
                    =
                    cat
                    .
                    getRootPath
                    (
                    )
                    ;
                    pathResourceCat
                    =
                    pathResourceCat
                    .
                    replace
                    (
                    site
                    ,
                    ""
                    )
                    ;
                    titleCat
                    =
                    cmso
                    .
                    readPropertyObject
                    (
                    pathResourceCat
                    ,
                    "Title_"
                    +
                    cmso
                    .
                    getRequestContext
                    (
                    )
                    .
                    getLocale
                    (
                    )
                    ,
                    false
                    )
                    .
                    getValue
                    (
                    cat
                    .
                    getTitle
                    (
                    )
                    )
                    ;
                    }
                    catch
                    (
                    CmsException
                    ex
                    )
                    {
                    titleCat
                    =
                    cat
                    .
                    getTitle
                    (
                    )
                    ;
                    }
                    if
                    (
                    fieldValues
                    .
                    contains
                    (
                    cat
                    .
                    getPath
                    (
                    )
                    )
                    )
                    out
                    .
                    println
                    (
                    "<option value=\""
                             +
                             cat
                             .
                             getPath
                             (
                             )
                             +
                    "\" selected=\"selected\">"
                    +
                    titleCat
                    +
                    "</option>"
                    )
                    ;
                    else
                    out
                    .
                    println
                    (
                    "<option value=\""
                             +
                             cat
                             .
                             getPath
                             (
                             )
                             +
                    "\">"
                    +
                    titleCat
                    +
                    "</option>"
                    )
                    ;
                    }
                    %>
                </select>
            </div>
        </c:when>
        <c:when test="${elem.value.FieldType == 'radio' }">
            <div class="form-group" id="filter-${status.count}">
                <div class="radio"><label for="${fieldName}"><input type="radio"
                                                                    name="${fieldName}"
                                                                    id="${fieldName}"
                                                                    value=""
                                                                    checked="checked"><fmt:message
                        key="formatter.filter.nocategory"/></label></div>
                <%
                String
                fieldValue
                =
                request
                .
                getParameter
                (
                fieldName
                )
                ;
                // si nos llega el parametro vacio guardamos la propiedad de categoria definida (si es que existe) como fieldvalue para que se muestre seleccionada
                if
                (
                StringUtils
                .
                isBlank
                (
                fieldValue
                )
                )
                {
                fieldValue
                =
                (
                String
                )
                request
                .
                getAttribute
                (
                "filtercategoryProperty"
                )
                ;
                }
                if
                (
                fieldValue
                ==
                null
                )
                fieldValue
                =
                ""
                ;
                if
                (
                tituloCatPadre
                !=
                null
                )
                {
                if
                (
                fieldValue
                .
                equals
                (
                categoryRoot
                )
                )
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                                             +
                                             fieldName
                                             +
                "\"><input type=\"radio\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\" checked=\"checked\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                                             +
                                             fieldName
                                             +
                "\"><input type=\"radio\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                }
                for
                (
                CmsCategory
                cat
                :
                categorias
                )
                {
                String
                titleCat
                =
                ""
                ;
                //Primero intentamos leer la categoria Title_LOCALE, si no nos quedamos con el Title
                try
                {
                String
                site
                =
                OpenCms
                .
                getSiteManager
                (
                )
                .
                getCurrentSite
                (
                cmso
                )
                .
                getSiteRoot
                (
                )
                ;
                String
                pathResourceCat
                =
                cat
                .
                getRootPath
                (
                )
                ;
                pathResourceCat
                =
                pathResourceCat
                .
                replace
                (
                site
                ,
                ""
                )
                ;
                titleCat
                =
                cmso
                .
                readPropertyObject
                (
                pathResourceCat
                ,
                "Title_"
                +
                cmso
                .
                getRequestContext
                (
                )
                .
                getLocale
                (
                )
                ,
                false
                )
                .
                getValue
                (
                cat
                .
                getTitle
                (
                )
                )
                ;
                }
                catch
                (
                CmsException
                ex
                )
                {
                titleCat
                =
                cat
                .
                getTitle
                (
                )
                ;
                }
                if
                (
                fieldValue
                .
                equals
                (
                cat
                .
                getPath
                (
                )
                )
                )
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                                             +
                                             fieldName
                                             +
                "\"><input type=\"radio\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\" checked=\"checked\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"radio\"><label for=\""
                                             +
                                             fieldName
                                             +
                "\"><input type=\"radio\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                }
                %>
            </div>
        </c:when>
        <c:when test="${elem.value.FieldType == 'checkbox' }">
            <div class="form-group" id="filter-${status.count}">
                <c:set var="fieldName" value="${value.Id }field-${status.count}"/>
                <%
                String
                [
                ]
                fieldValuesArray
                =
                request
                .
                getParameterValues
                (
                fieldName
                )
                ;
                List
                <
                String
                >
                fieldValues
                =
                null
                ;
                // si nos llega el parametro vacio guardamos la propiedad de categoria definida (si es que existe) como fieldvalue para que se muestre seleccionada
                String
                categoryProperty
                =
                (
                String
                )
                request
                .
                getAttribute
                (
                "filtercategoryProperty"
                )
                ;

                if
                (
                fieldValuesArray
                !=
                null
                )
                fieldValues
                =
                Arrays
                .
                asList
                (
                fieldValuesArray
                )
                ;
                else
                if
                (
                !
                StringUtils
                .
                isBlank
                (
                categoryProperty
                )
                )
                {
                fieldValues
                =
                new
                ArrayList
                <
                String
                >
                (
                )
                ;
                fieldValues
                .
                add
                (
                categoryProperty
                )
                ;
                }
                else
                fieldValues
                =
                new
                ArrayList
                <
                String
                >
                (
                )
                ;
                if
                (
                tituloCatPadre
                !=
                null
                )
                {
                if
                (
                fieldValues
                .
                contains
                (
                categoryRoot
                )
                )
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                                                +
                                                fieldName
                                                +
                "\"><input type=\"checkbox\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\" checked=\"checked\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                                                +
                                                fieldName
                                                +
                "\"><input type=\"checkbox\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                categoryRoot
                +
                "\">"
                +
                tituloCatPadre
                +
                "</label></div>"
                )
                ;
                }
                for
                (
                CmsCategory
                cat
                :
                categorias
                )
                {
                String
                titleCat
                =
                ""
                ;
                //Primero intentamos leer la categoria Title_LOCALE, si no nos quedamos con el Title
                try
                {
                String
                site
                =
                OpenCms
                .
                getSiteManager
                (
                )
                .
                getCurrentSite
                (
                cmso
                )
                .
                getSiteRoot
                (
                )
                ;
                String
                pathResourceCat
                =
                cat
                .
                getRootPath
                (
                )
                ;
                pathResourceCat
                =
                pathResourceCat
                .
                replace
                (
                site
                ,
                ""
                )
                ;
                titleCat
                =
                cmso
                .
                readPropertyObject
                (
                pathResourceCat
                ,
                "Title_"
                +
                cmso
                .
                getRequestContext
                (
                )
                .
                getLocale
                (
                )
                ,
                false
                )
                .
                getValue
                (
                cat
                .
                getTitle
                (
                )
                )
                ;
                }
                catch
                (
                CmsException
                ex
                )
                {
                titleCat
                =
                cat
                .
                getTitle
                (
                )
                ;
                }
                if
                (
                fieldValues
                .
                contains
                (
                cat
                .
                getPath
                (
                )
                )
                )
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                                                +
                                                fieldName
                                                +
                "\"><input type=\"checkbox\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\" checked=\"checked\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                else
                out
                .
                println
                (
                "<div class=\"checkbox\"><label for=\""
                                                +
                                                fieldName
                                                +
                "\"><input type=\"checkbox\" id=\""
                           +
                           fieldName
                           +
                "\" name=\""
                +
                fieldName
                +
                "\" value=\""
                +
                cat
                .
                getPath
                (
                )
                +
                "\">"
                +
                titleCat
                +
                "</label></div>"
                )
                ;
                }
                %>
            </div>
        </c:when>
        </c:choose>-->
</template>

<script>
    import FilterCategorySelect from './FilterCategorySelect.vue'
    export default
    {
        props:{
            vFilter:{
                type: Object,
                required: true
            }
        },
        components:{
            "v-filter-category-select": FilterCategorySelect
        }
    }
</script>

<style>
</style>
